# The following code is generated by ChatGPT, and the prompt used is "how to plot reading from arduino using python".
# The generated code is then refined many times by telling it the problem I encountered, then it generated the new and improved code.

import serial
import time
import matplotlib.pyplot as plt

arduino = serial.Serial('COM6', 9600, timeout=0.1)  

# Set up for plotting
plt.ion()  # Enable interactive mode for live plotting
fig, ax = plt.subplots()
x_vals = []  # List to store x values (time or number of readings)
y_vals = []  # List to store y values (sensor readings)

# Real-time plotting loop
try:
    while True:
        # Read the data from the Serial port
        if arduino.in_waiting > 0:  # Check if there's data available
            data = arduino.readline().decode('utf-8').strip()  # Read and decode data
            try:
                sensor_value = float(data)  # Convert the data to an integer
                print(f"Angle in degress: {sensor_value}")
                
                # Update the x and y lists
                x_vals.append(len(x_vals))  # Append the time or number of reading
                y_vals.append(sensor_value)  # Append the sensor value

                # Update the plot
                ax.clear()
                ax.plot(x_vals, y_vals)
                ax.set_xlabel('Data point')
                ax.set_ylabel('Angle in degrees')
                ax.set_title('Real-Time Angle computed via only gyroscope')
                ax.legend()
                plt.draw()
                plt.pause(0.00000000001)  # Pause to allow for the plot to update

            except ValueError:
                print("Invalid data received.")

except KeyboardInterrupt:
    #raise SystemExit
    print("Program stopped.")

finally:
    arduino.close()  # Close the serial connection when done